name: num_to_word_en_vi
description: A plugin project to convert numbers to words with Vietnamese/English language.
version: 1.0.1
homepage: https://github.com/DoTungLam96/number_to_word_vi_en.git

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
